package:
  name: "agb"
  version: "0.4"

source:
  git_rev: 4c1fad6
  git_url: https://github.com/almiheenko/AGB

build:
  number: 4

requirements:
  host:
    - python
    - setuptools

  build:
    - python
    - six
    - cython
    - minimap2
    - nxmetis
    - quast >=5.0

  run:
    - python
    - six
    - cython
    - networkx
    - gfapy
    - minimap2
    - nxmetis
    - quast >=5.0

test:
  import:
    - nxmetis

about:
  home: https://github.com/almiheenko/AGB
  license: GPLv2
  license_file: ../LICENSE
