package:
  name: "agv"
  version: "0.1"

source:
  git_rev: a623525
  git_url: https://github.com/almiheenko/AGV

build:
  number: 2

requirements:
  host:
    - python
    - setuptools

  build:
    - python
    - six
    - cython
    - minimap2
    - nxmetis

  run:
    - python
    - six
    - cython
    - networkx
    - gfapy
    - minimap2
    - nxmetis

test:
  import:
    - nxmetis

about:
  home: https://github.com/almiheenko/AGV
  license: BSD3
  license_file: ../LICENSE
