package:
  name: "agv"
  version: "0.1"

source:
  git_rev: e5ea231
  git_url: https://github.com/almiheenko/AGV

build:
  number: 1

requirements:
  host:
    - python
    - setuptools

  build:
    - python
    - six
    - cython
    - minimap2

  run:
    - python
    - six
    - cython
    - networkx
    - gfapy
    - minimap2

test:

about:
  home: https://github.com/almiheenko/AGV
  license: BSD3
  license_file: ../LICENSE
